import Foundation

@main
struct ProxyBuildInfoTool {
    static func main() throws {
        let options = try Options.parse(arguments: CommandLine.arguments)
        let outputURL = URL(fileURLWithPath: options.outputPath)
        let version = BuildInfoVersionResolver.resolve(
            environmentVersion: options.environmentVersion,
            packageDirectory: URL(fileURLWithPath: options.packageDirectoryPath)
        )
        let source = BuildInfoVersionResolver.generatedSource(version: version)

        try FileManager.default.createDirectory(
            at: outputURL.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        if let existingSource = try? String(contentsOf: outputURL, encoding: .utf8),
           existingSource == source
        {
            return
        }

        try source.write(to: outputURL, atomically: true, encoding: .utf8)
    }
}

private struct Options {
    let outputPath: String
    let packageDirectoryPath: String
    let environmentVersion: String?

    static func parse(arguments: [String]) throws -> Self {
        var outputPath: String?
        var packageDirectoryPath: String?
        var environmentVersion: String?
        var index = 1

        while index < arguments.count {
            switch arguments[index] {
            case "--output":
                guard index + 1 < arguments.count else {
                    throw ProxyBuildInfoToolError.message("--output requires a value")
                }
                outputPath = arguments[index + 1]
                index += 2
            case "--package-directory":
                guard index + 1 < arguments.count else {
                    throw ProxyBuildInfoToolError.message("--package-directory requires a value")
                }
                packageDirectoryPath = arguments[index + 1]
                index += 2
            case "--environment-version":
                guard index + 1 < arguments.count else {
                    throw ProxyBuildInfoToolError.message("--environment-version requires a value")
                }
                environmentVersion = arguments[index + 1]
                index += 2
            default:
                throw ProxyBuildInfoToolError.message("unknown option: \(arguments[index])")
            }
        }

        guard let outputPath else {
            throw ProxyBuildInfoToolError.message("--output is required")
        }
        guard let packageDirectoryPath else {
            throw ProxyBuildInfoToolError.message("--package-directory is required")
        }

        return Self(
            outputPath: outputPath,
            packageDirectoryPath: packageDirectoryPath,
            environmentVersion: environmentVersion
        )
    }
}

private enum BuildInfoVersionResolver {
    static func resolve(
        environmentVersion: String?,
        packageDirectory: URL,
        gitDescribe: (URL) throws -> String? = defaultGitDescribe(in:)
    ) -> String {
        if let version = normalized(environmentVersion) {
            return version
        }

        if let version = try? gitDescribe(packageDirectory),
           let normalizedVersion = normalized(version)
        {
            return normalizedVersion
        }

        return "dev"
    }

    static func generatedSource(version: String) -> String {
        """
        // Generated by ProxyBuildInfoTool. Do not edit.

        enum ProxyBuildGeneratedInfo {
            static let version = "\(escapedStringLiteral(version))"
        }
        """
    }

    private static func normalized(_ value: String?) -> String? {
        guard let raw = value?.trimmingCharacters(in: .whitespacesAndNewlines), !raw.isEmpty else {
            return nil
        }
        return raw
    }

    private static func defaultGitDescribe(in packageDirectory: URL) throws -> String? {
        let process = Process()
        let outputPipe = Pipe()

        process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
        process.arguments = [
            "-C", packageDirectory.path,
            "describe",
            "--tags",
            "--always",
            "--dirty",
        ]
        process.standardOutput = outputPipe
        process.standardError = Pipe()

        try process.run()
        process.waitUntilExit()

        guard process.terminationStatus == 0 else {
            return nil
        }

        let data = outputPipe.fileHandleForReading.readDataToEndOfFile()
        return String(data: data, encoding: .utf8)
    }

    private static func escapedStringLiteral(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }
}

private enum ProxyBuildInfoToolError: Error, CustomStringConvertible {
    case message(String)

    var description: String {
        switch self {
        case .message(let text):
            return text
        }
    }
}
